import { useCallback, useEffect, useState } from 'react'
import { VolunteerAssignments, VolunteerAvailableSlots, type AvailableVolunteerSlot, type ShiftRole, type ShiftRoleCoverage, type VolunteerAssignment } from '../scheduling'
import { getSupabaseBrowserClient } from '../../lib/supabase'

interface AssignmentRow { assignment_id: string; shift_id: string; starts_at: string; ends_at: string; title: string; location_label: string | null; assignment_status: 'pending' | 'assigned' | 'confirmed' | 'absence_requested'; roles: ShiftRole[] | null; role_instructions: Partial<Record<ShiftRole, string | null>> | null; role_notice_pending: boolean }
interface AvailableShiftRow { id: string; starts_at: string; ends_at: string; volunteer_count: number; role_coverage: ShiftRoleCoverage[] | null; title: string }
interface VolunteerScheduleProps { volunteerName: string }
type Confirmation = { action: 'claim' | 'cancel'; slot: AvailableVolunteerSlot }

function ShiftConfirmationDialog({ confirmation, isSubmitting, onClose, onConfirm }: { confirmation: Confirmation; isSubmitting: boolean; onClose: () => void; onConfirm: () => void }) {
  const isClaim = confirmation.action === 'claim'
  return <div aria-labelledby="shift-confirmation-heading" aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-altar-ink/45 p-6" role="dialog"><section className="w-full max-w-md border-t-2 border-altar-gold bg-altar-parchment p-6 shadow-xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-altar-sage">{confirmation.slot.label}</p><h2 className="mt-2 font-display text-2xl text-altar-teal" id="shift-confirmation-heading">{isClaim ? 'Serve at this shift?' : 'Cancel this shift?'}</h2><p className="mt-4 leading-7 text-altar-ink/80">{isClaim ? "Are you sure you'd like to sign-up for this shift?" : "Are you sure you'd like to cancel your sign-up for this shift?"}</p><div className="mt-6 flex flex-wrap justify-end gap-3"><button className="focus-ring rounded-sm border border-altar-teal px-4 py-2 text-sm font-semibold text-altar-teal" disabled={isSubmitting} onClick={onClose} type="button">Keep this shift</button><button className={isClaim ? 'button-primary' : 'focus-ring rounded-sm bg-altar-teal px-4 py-2 text-sm font-semibold text-white'} disabled={isSubmitting} onClick={onConfirm} type="button">{isSubmitting ? (isClaim ? 'Signing up…' : 'Cancelling…') : (isClaim ? 'Yes, sign me up' : 'Yes, cancel this shift')}</button></div></section></div>
}

export function VolunteerSchedule({ volunteerName }: VolunteerScheduleProps) {
  const [slots, setSlots] = useState<AvailableVolunteerSlot[]>([]); const [assignments, setAssignments] = useState<VolunteerAssignment[]>([]); const [claimingSlotId, setClaimingSlotId] = useState<string>(); const [cancellingSlotId, setCancellingSlotId] = useState<string>(); const [dismissingRoleNoticeId, setDismissingRoleNoticeId] = useState<string>(); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [claimError, setClaimError] = useState<{ slotId: string; message: string } | null>(null); const [locallyClaimedShiftIds, setLocallyClaimedShiftIds] = useState<Set<string>>(() => new Set()); const [confirmation, setConfirmation] = useState<Confirmation | null>(null)
  const load = useCallback(async (extraClaimedShiftIds: ReadonlySet<string> = new Set()) => {
    const client = getSupabaseBrowserClient()
    const [{ data: available, error: availableError }, { data: assigned, error: assignedError }] = await Promise.all([client.rpc('list_available_volunteer_shifts', { p_limit: 50 }), client.rpc('list_my_shift_assignments', { p_limit: 50 })])
    if (availableError || assignedError) { setError('Your private schedule could not be loaded. Please refresh and try again.'); return }
    const activeAssignments = ((assigned ?? []) as AssignmentRow[]).filter((assignment) => assignment.assignment_status === 'assigned' || assignment.assignment_status === 'confirmed')
    const assignmentIdByShift = new Map(activeAssignments.map((assignment) => [assignment.shift_id, assignment.assignment_id]))
    setAssignments(((assigned ?? []) as AssignmentRow[]).map((assignment) => ({ id: assignment.assignment_id, startsAt: assignment.starts_at, endsAt: assignment.ends_at, title: assignment.title, locationLabel: assignment.location_label ?? undefined, status: assignment.assignment_status, roles: assignment.roles ?? [], roleInstructions: Object.fromEntries(Object.entries(assignment.role_instructions ?? {}).filter(([, instruction]) => Boolean(instruction))) as Partial<Record<ShiftRole, string>>, roleNoticePending: assignment.role_notice_pending })))
    setSlots(((available ?? []) as AvailableShiftRow[]).map((shift) => ({ id: shift.id, startsAt: shift.starts_at, endsAt: shift.ends_at, label: shift.title, volunteerCount: Number(shift.volunteer_count), roleCoverage: shift.role_coverage ?? [], isScheduled: assignmentIdByShift.has(shift.id) || locallyClaimedShiftIds.has(shift.id) || extraClaimedShiftIds.has(shift.id), assignmentId: assignmentIdByShift.get(shift.id) })))
  }, [locallyClaimedShiftIds])
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [load])
  const claim = async (slot: AvailableVolunteerSlot) => { setClaimingSlotId(slot.id); setError(null); setMessage(null); setClaimError(null); const { data, error: rpcError } = await getSupabaseBrowserClient().rpc('claim_open_shift', { p_shift_id: slot.id }); setClaimingSlotId(undefined); if (rpcError) { const message = rpcError.message || 'This shift could not be saved. Please refresh and try again.'; setClaimError({ slotId: slot.id, message }); await load(); return }; const assignmentId = (data as { id?: string } | null)?.id; setLocallyClaimedShiftIds((ids) => new Set(ids).add(slot.id)); setSlots((current) => current.map((currentSlot) => currentSlot.id === slot.id ? { ...currentSlot, isScheduled: true, assignmentId, volunteerCount: currentSlot.volunteerCount + 1 } : currentSlot)); setMessage(`You’re scheduled for ${slot.label}. A coordinator has been notified and will assign your function.`); await load(new Set([slot.id])) }
  const cancel = async (slot: AvailableVolunteerSlot) => { if (!slot.assignmentId) return; setCancellingSlotId(slot.id); setError(null); setMessage(null); setClaimError(null); const { error: rpcError } = await getSupabaseBrowserClient().rpc('cancel_my_shift_assignment', { p_assignment_id: slot.assignmentId }); setCancellingSlotId(undefined); if (rpcError) { const message = rpcError.message || 'This shift could not be cancelled. Please refresh and try again.'; setClaimError({ slotId: slot.id, message }); await load(); return }; setLocallyClaimedShiftIds((ids) => { const next = new Set(ids); next.delete(slot.id); return next }); setSlots((current) => current.map((currentSlot) => currentSlot.id === slot.id ? { ...currentSlot, isScheduled: false, assignmentId: undefined, volunteerCount: Math.max(0, currentSlot.volunteerCount - 1) } : currentSlot)); setMessage(`You’re no longer scheduled for ${slot.label}.`); await load() }
  const respond = async (assignmentId: string, response: 'accepted' | 'declined') => { setError(null); const { error: responseError } = await getSupabaseBrowserClient().rpc('respond_to_shift_invitation', { p_assignment_id: assignmentId, p_response: response }); if (responseError) { setError('That invitation could not be updated. Please refresh and try again.'); return }; await load() }
  const dismissRoleNotice = async (assignmentId: string) => { setDismissingRoleNoticeId(assignmentId); setError(null); const { error: dismissError } = await getSupabaseBrowserClient().rpc('acknowledge_my_role_assignment_notice', { p_assignment_id: assignmentId }); setDismissingRoleNoticeId(undefined); if (dismissError) { setError('That role update could not be marked as seen. Please try again.'); return }; setAssignments((current) => current.map((assignment) => assignment.id === assignmentId ? { ...assignment, roleNoticePending: false } : assignment)) }
  const confirm = async () => { if (!confirmation) return; const { action, slot } = confirmation; await (action === 'claim' ? claim(slot) : cancel(slot)); setConfirmation(null) }
  return <>{error ? <p className="mx-auto mt-8 max-w-6xl border-l-2 border-altar-gold bg-white/50 p-4 text-sm text-altar-ink" role="alert">{error}</p> : null}{message ? <p className="mx-auto mt-8 max-w-6xl border-l-2 border-altar-teal bg-white/50 p-4 text-sm text-altar-ink" role="status">{message}</p> : null}<VolunteerAssignments assignments={assignments} dismissingRoleNoticeId={dismissingRoleNoticeId} onDismissRoleNotice={(id) => void dismissRoleNotice(id)} onRespondToInvitation={(id, response) => void respond(id, response)} /><VolunteerAvailableSlots cancellingSlotId={cancellingSlotId} claimError={claimError} claimingSlotId={claimingSlotId} onCancelSlot={(slot) => setConfirmation({ action: 'cancel', slot })} onClaimSlot={(slot) => setConfirmation({ action: 'claim', slot })} periodLabel={`Welcome, ${volunteerName}`} slots={slots} />{confirmation ? <ShiftConfirmationDialog confirmation={confirmation} isSubmitting={claimingSlotId === confirmation.slot.id || cancellingSlotId === confirmation.slot.id} onClose={() => setConfirmation(null)} onConfirm={() => void confirm()} /> : null}</>
}
