import { SHIFT_ROLE_LABELS, type VolunteerAssignmentsProps } from './types'

const churchTimeZone = 'America/Denver'
function formatDateTime(value: string) {
  return new Intl.DateTimeFormat('en-US', { weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', timeZone: churchTimeZone }).format(new Date(value))
}

/** A volunteer's own assignment projection. It contains no other person's schedule. */
export function VolunteerAssignments({ assignments, onRespondToInvitation, onDismissRoleNotice, dismissingRoleNoticeId }: VolunteerAssignmentsProps) {
  return <section aria-labelledby="my-assignments-heading" className="mx-auto max-w-4xl px-6 pt-12 sm:px-10 lg:px-16">
    <div className="border-t border-altar-sage/30 pt-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-altar-teal">Your private schedule</p><h2 className="mt-3 font-display text-3xl text-altar-teal" id="my-assignments-heading">Your upcoming assignments</h2>
      {assignments.length ? <ul className="mt-5 divide-y divide-altar-sage/25 border-y border-altar-sage/25">{assignments.map((assignment) => <li className="grid gap-2 py-5 sm:grid-cols-[12rem_1fr]" key={assignment.id}><p className="text-sm font-semibold text-altar-teal">{formatDateTime(assignment.startsAt)}</p><div><h3 className="font-display text-xl text-altar-ink">{assignment.title}</h3>{assignment.roles?.length ? <><p className="mt-2 text-sm font-semibold text-altar-teal">Serving as: {assignment.roles.map((role) => SHIFT_ROLE_LABELS[role]).join(' · ')}</p><dl className="mt-3 space-y-2 text-sm leading-6 text-altar-ink/75">{assignment.roles.map((role) => assignment.roleInstructions?.[role] ? <div key={role}><dt className="font-semibold text-altar-teal">{SHIFT_ROLE_LABELS[role]}</dt><dd>{assignment.roleInstructions[role]}</dd></div> : null)}</dl></> : null}{assignment.roleNoticePending ? <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-l-2 border-altar-gold bg-altar-gold/10 px-3 py-2 text-sm text-altar-ink" role="status"><span>Your coordinator has updated your serving role. Please review it above.</span>{onDismissRoleNotice ? <button className="focus-ring text-sm font-semibold text-altar-teal underline underline-offset-4" disabled={dismissingRoleNoticeId === assignment.id} onClick={() => onDismissRoleNotice(assignment.id)} type="button">{dismissingRoleNoticeId === assignment.id ? 'Dismissing…' : 'Dismiss'}</button> : null}</div> : null}<p className="mt-2 text-xs font-semibold uppercase tracking-[0.12em] text-altar-sage">{assignment.status === 'pending' ? 'Pending your response' : assignment.status === 'absence_requested' ? 'Absence requested' : assignment.status === 'confirmed' ? 'Confirmed' : assignment.roles?.length ? 'Scheduled' : 'Role assignment pending'}</p>{assignment.status === 'pending' && onRespondToInvitation ? <div className="mt-4 flex flex-wrap gap-3"><button className="button-primary" onClick={() => onRespondToInvitation(assignment.id, 'accepted')} type="button">Accept invitation</button><button className="focus-ring rounded-sm border border-altar-teal px-4 py-2 text-sm font-semibold text-altar-teal" onClick={() => onRespondToInvitation(assignment.id, 'declined')} type="button">Decline</button></div> : null}</div></li>)}</ul> : <p className="mt-5 border-l-2 border-altar-stone bg-white/45 p-4 text-sm leading-6 text-altar-ink/70">You do not have any upcoming assignments yet. Choose a prayer shift when you are ready to serve.</p>}</div>
  </section>
}
